# Generated by Django 5.0.1 on 2024-09-11 10:20

import django.db.models.deletion
import tracks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('num_of_plays', models.PositiveBigIntegerField(default=0)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('path', models.FileField(default='', upload_to=tracks.models.track_upload_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_with_track', to='albums.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
