# Generated by Django 5.0.1 on 2024-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_tracksinplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
