# Generated by Django 5.0.1 on 2024-09-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_public'),
        ('tracks', '0003_alter_track_album_liked_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksinplaylist',
            name='track',
        ),
        migrations.AddField(
            model_name='tracksinplaylist',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='tracks.track'),
            preserve_default=False,
        ),
    ]
