# Generated by Django 5.0.1 on 2024-09-23 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_remove_tracksinplaylist_track_tracksinplaylist_track'),
        ('tracks', '0003_alter_track_album_liked_played'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksinplaylist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_in_playlist', to='tracks.track'),
        ),
        migrations.AlterField(
            model_name='tracksinplaylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL),
        ),
    ]
