# Generated by Django 5.0.1 on 2024-09-07 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('num_of_tracks', models.PositiveIntegerField(default=0)),
                ('cover', models.ImageField(blank=True, upload_to='static/album_covers/')),
                ('artists', models.ManyToManyField(related_name='albums_artists', to='artists.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
