# Generated by Django 5.0.1 on 2024-09-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
