# Generated by Django 5.0.1 on 2024-04-22 20:57

import SpotifyApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='track',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='artist_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='played',
            name='played_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='path',
            field=models.FileField(default='', upload_to=SpotifyApp.models.track_upload_path),
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='track_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='albums_artists', to='SpotifyApp.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='artists_albums', to='SpotifyApp.album'),
        ),
        migrations.AlterField(
            model_name='liked',
            name='liked_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TracksInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tracks_from_playlist', to='SpotifyApp.playlist')),
                ('track', models.ManyToManyField(related_name='playlist_tracks', to='SpotifyApp.track')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks_in_playlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
